### ISSUE TITLE
Fails to build in RN 0.78.0-rc.5

### ISSUE THREAD

**Issue by mstrokin** [kirillzyusko/react-native-keyboard-controller#806]
**Describe the bug**
Bunch of errors when trying to update the project to 0.78.0-rc.5 (0.78 will be released next week)

e: android/src/main/java/com/reactnativekeyboardcontroller/modal/ModalAttachedWatcher.kt:23:1 Class 'ModalAttachedWatcher' is not abstract and does not implement abstract member 'onEventDispatch'.
e: android/src/main/java/com/reactnativekeyboardcontroller/modal/ModalAttachedWatcher.kt:33:3 'onEventDispatch' overrides nothing.
e: android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/OverKeyboardViewGroup.kt:96:1 Class 'OverKeyboardRootViewGroup' is not abstract and does not implement abstract member 'onChildStartedNativeGesture'.
e: android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/OverKeyboardViewGroup.kt:165:3 'onChildStartedNativeGesture' overrides nothing.
e: android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/RootViewCompat.kt:15:3 'onChildStartedNativeGesture' overrides nothing.
e: android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/RootViewCompat.kt:16:39 Argument type mismatch: actual type is 'android.view.MotionEvent?', but 'android.view.MotionEvent' was expected.

**Comment by kirillzyusko** [comment]
Thanks @mstrokin 

I only added RN 77 support recently, but thank you for creating this issue! Will try to add support for RN 0.78 soon!

**Comment by kirillzyusko** [comment]
@mstrokin the fix will be published in `1.16.4`. In the meantime you can use patch-package and apply a patch from PRs linked to that issue.

Thank you for raising this problem!

**Comment by faljabi** [comment]
Hi,

Is it possible to have a quick release supporting react native 0.78?

**Comment by kirillzyusko** [comment]
@faljabi I'll try to prepare a new release tomorrow 🤞

**Comment by faljabi** [comment]
Much appreciated ❤️

**Comment by kirillzyusko** [comment]
Fix published in `1.16.4`
