### ISSUE TITLE
ERROR  [Error: Uncaught (in promise, id: 1) TypeError: _bindings.KeyboardControllerNative.viewPositionInWindow is not a function (it is undefined)]

### ISSUE THREAD

**Issue by branaust** [kirillzyusko/react-native-keyboard-controller#1369]
**Describe the bug**
Getting an error thrown when updating from 1.21.0-beta.3 to 1.21.0

**Code snippet**
```
// App.tsx (bare React Native or Expo project)
import React from 'react';
import { TextInput, View } from 'react-native';
import {
  KeyboardProvider,
  KeyboardAwareScrollView,
} from 'react-native-keyboard-controller';

function Screen() {
  return (
    <KeyboardAwareScrollView>
      <View style={{ height: 800 }}>
        <TextInput
          placeholder="Type here"
          style={{ borderWidth: 1, margin: 20, padding: 10 }}
        />
      </View>
    </KeyboardAwareScrollView>
  );
}

export default function App() {
  return (
    <KeyboardProvider>
      <Screen />
    </KeyboardProvider>
  );
}
```

**To Reproduce**

1. Install `react-native-keyboard-controller@1.21.0`
2. Wrap app with `<KeyboardProvider>`
3. Use `<KeyboardAwareScrollView>` with a `TextInput` inside
4. Focus the input on a physical device or simulator

Expected:** Keyboard avoidance works  
**Actual:** `TypeError: _bindings.KeyboardControllerNative.viewPositionInWindow is not a function (it is undefined)

**Additional context**
Error didnt get thrown in the beta

**Comment by kirillzyusko** [comment]
Hey @branaust 

You need to re-compile the app. I changed a code and added new native functions, so after updating a lib you need to re-compile native code in order to make everything working 🤞

**Comment by kirillzyusko** [comment]
And yes, this code was added after `1.21.0-beta.3`, this is why you are getting errors 🤔

**Comment by branaust** [comment]
roger that. thanks

**Comment by branaust** [comment]
I recompiled the app. the issue persists.

**Comment by kirillzyusko** [comment]
@branaust are you using iOS/Android? new/old architecture? I'll try to reproduce this issue in example app 👀

**Comment by kirillzyusko** [comment]
I just tested both iOS/Android Fabric+Paper architecture and I don't see any errors, so I'm afraid I would need a repro example to investigate this problem further 😔

**Comment by kirillzyusko** [comment]
@branaust I'm getting many new issues, so I'm going to close this one as I'm unable to reproduce it. If you manage to prepare a minimal reproduction example, then feel free to share it here (ideally GitHub repo) and I'll re-open the issue!
