### ISSUE TITLE
[Android] compileReleaseKotlin fails on RN < 0.74 since 1.21.0: Unresolved reference ClippingScrollViewDecoratorViewManager (wrong package declaration)

### ISSUE THREAD

**Issue by ahulterstrom** [kirillzyusko/react-native-keyboard-controller#1585]
**Describe the bug**

Android release builds fail on React Native < 0.74 (old architecture) since v1.21.0:

```
> Task :react-native-keyboard-controller:compileReleaseKotlin FAILED

e: .../android/src/turbo/java/com/reactnativekeyboardcontroller/KeyboardControllerPackage.kt:63:7
   Unresolved reference: ClippingScrollViewDecoratorViewManager
```

**Root cause**

`ClippingScrollViewDecoratorViewManager.kt` in both the `paper` and `fabric` source sets declares:

```kotlin
package java.com.reactnativekeyboardcontroller
```

instead of `package com.reactnativekeyboardcontroller` — it looks like the `java/` source-root folder got baked into the package name when the file was created. Every other file in the library is in `com.reactnativekeyboardcontroller`.

The `base` variant of `KeyboardControllerPackage.kt` (used when RN >= 0.74) compensates with an explicit import, so most users never hit this:

```kotlin
import java.com.reactnativekeyboardcontroller.ClippingScrollViewDecoratorViewManager
```

But the `turbo` variant (compiled when `shouldUseBaseReactPackage()` is false, i.e. RN < 0.74) references the class unqualified with no import, so it only resolves if the class is in `com.reactnativekeyboardcontroller` — which it isn't. Hence the compile failure on every RN < 0.74 build since the component was introduced in 1.21.0. Still present on `main` as of today.

**Suggested fix**

Rename the package in `android/src/paper/.../ClippingScrollViewDecoratorViewManager.kt` and `android/src/fabric/.../ClippingScrollViewDecoratorViewManager.kt` to `com.reactnativekeyboardcontroller`, and drop the `java.com.` import from the `base` `KeyboardControllerPackage.kt`. (As a side benefit, that moves the class out of the `java.*` namespace, which is prohibited on the JVM ClassLoader and only works on Android because classes load from dex.)

**To Reproduce**

1. RN 0.72.x app, old architecture (`newArchEnabled=false`)
2. Install `react-native-keyboard-controller` >= 1.21.0
3. `cd android && ./gradlew :react-native-keyboard-controller:compileReleaseKotlin`
4. Compilation fails with the unresolved reference above

**Expected behavior**

The library compiles on all RN versions it supports.

**Workaround**

patch-package adding the same import line the `base` variant uses to `android/src/turbo/.../KeyboardControllerPackage.kt`:

```diff
 import com.reactnativekeyboardcontroller.modules.statusbar.StatusBarManagerCompatModuleImpl
+import java.com.reactnativekeyboardcontroller.ClippingScrollViewDecoratorViewManager
```

**Environment**

- Desktop OS: macOS 15 / ubuntu-latest CI
- RN version: 0.72.3
- RN architecture: old/paper
- JS engine: Hermes
- Library version: 1.22.3 (affects 1.21.0 through 1.22.3 and current `main`)

**Comment by kirillzyusko** [comment]
Hey @ahulterstrom 

Could you please check if https://github.com/kirillzyusko/react-native-keyboard-controller/pull/1587 fixes a problem for you? 🙏 

This is basically the suggested fix that you described, but implemented in code 🙈

**Comment by ahulterstrom** [comment]
@kirillzyusko I applied the diff from #1587 to 1.22.3 with patch-package and it fixes the compile error on RN 0.72.3. Both `compileDebugKotlin` and `compileReleaseKotlin` pass, and the app runs fine on a device.

A note for anyone stuck on RN < 0.74 until this is released: if you use the manual workaround, the `import java.com...` line has to go into the turbo variant of `KeyboardControllerPackage.kt`, not the base one. `shouldUseBaseReactPackage()` returns false below 0.74, so the base variant never gets compiled on those versions. Once #1587 lands, no workaround is needed at all.

While testing on RN 0.72.3 I ran into two more crashes in 1.22.3. Both are in the JS code, unrelated to this Kotlin fix, and still present on main. Happy to open separate issues or send a PR.

1. `src/specs/ClippingScrollViewDecoratorViewNativeComponent.ts` imports `codegenNativeComponent` from the `react-native` root package. That export was only added in RN 0.80.0. On anything older it comes back undefined, the spec file throws while the module loads (`TypeError: 0, _reactNative.codegenNativeComponent is not a function (it is undefined)`), and the whole library then fails to import, which shows up as `Cannot read property 'KeyboardProvider' of undefined`. All the other spec files import it from `react-native/Libraries/Utilities/codegenNativeComponent`, which works on every version. Changing this one file to match them fixes it.

2. `useEventHandlerRegistration` in `internal.ts` doesn't work with reanimated older than 3.8.0. Up to 3.7, `useEvent` returns a ref, so the object with `registerForEvents` is on `handler.current`. The code only checks for the newer shapes (a `workletEventHandler` property, or the handler itself), so on older reanimated it crashes when `KeyboardProvider` mounts: `TypeError: currentHandler.registerForEvents is not a function`. peerDependencies allows `react-native-reanimated >= 3.0.0`, so this range should be supported. Adding an `else if ("current" in currentHandler)` branch to both the register and unregister paths fixes it. I verified that with reanimated 3.3.0.

I have both fixes running locally via patch-package and can turn them into a PR if you'd like.

**Comment by kirillzyusko** [comment]
Yes @ahulterstrom 

PRs are highly appreciated, thank you!
